package featurea.createFont.examples

import java.awt.Canvas
import java.awt.Font
import java.awt.Font.PLAIN
import java.awt.font.FontRenderContext
import java.awt.font.TextAttribute
import kotlin.math.round

// https://programtalk.com/vs/jpexs-decompiler/libsrc/ffdec_lib/src/com/jpexs/decompiler/flash/helpers/FontHelper.java/

fun test3() {
    val font = Font("Arial", PLAIN, 16)

    /*println(getFontCharsKerning(font, 89.toChar(), 58.toChar()))*/

    println(getFontCharsKerning(font, 49.toChar(), 49.toChar()) == -1)
    println(getFontCharsKerning(font, 89.toChar(), 58.toChar()) == -1)
    println(getFontCharsKerning(font, 89.toChar(), 59.toChar()) == -1)
    println(getFontCharsKerning(font, 80.toChar(), 65.toChar()) == -1)
    println(getFontCharsKerning(font, 65.toChar(), 84.toChar()) == -1)
    println(getFontCharsKerning(font, 65.toChar(), 86.toChar()) == -1)
    println(getFontCharsKerning(font, 76.toChar(), 87.toChar()) == -1)
    println(getFontCharsKerning(font, 76.toChar(), 89.toChar()) == -1)
    println(getFontCharsKerning(font, 86.toChar(), 97.toChar()) == -1)
    println(getFontCharsKerning(font, 89.toChar(), 101.toChar()) == -1)
    println(getFontCharsKerning(font, 84.toChar(), 105.toChar()) == -1)
    println(getFontCharsKerning(font, 89.toChar(), 111.toChar()) == -1)
    println(getFontCharsKerning(font, 89.toChar(), 112.toChar()) == -1)
    println(getFontCharsKerning(font, 89.toChar(), 113.toChar()) == -1)
    println(getFontCharsKerning(font, 84.toChar(), 114.toChar()) == -1)
    println(getFontCharsKerning(font, 84.toChar(), 115.toChar()) == -2)
    println(getFontCharsKerning(font, 84.toChar(), 117.toChar()) == -1)
    println(getFontCharsKerning(font, 89.toChar(), 118.toChar()) == -1)
    println(getFontCharsKerning(font, 84.toChar(), 119.toChar()) == -1)
    println(getFontCharsKerning(font, 76.toChar(), 121.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1079.toChar()) == -1)
    println(getFontCharsKerning(font, 1056.toChar(), 1103.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1074.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1075.toChar()) == -1)
    println(getFontCharsKerning(font, 1042.toChar(), 1040.toChar()) == -1)
    println(getFontCharsKerning(font, 1061.toChar(), 1057.toChar()) == -1)
    println(getFontCharsKerning(font, 119.toChar(), 44.toChar()) == -1)
    println(getFontCharsKerning(font, 1042.toChar(), 1071.toChar()) == -1)
    println(getFontCharsKerning(font, 1070.toChar(), 1044.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1093.toChar()) == -1)
    println(getFontCharsKerning(font, 1075.toChar(), 44.toChar()) == -2)
    println(getFontCharsKerning(font, 89.toChar(), 117.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1051.toChar()) == -1)
    println(getFontCharsKerning(font, 119.toChar(), 46.toChar()) == -1)
    println(getFontCharsKerning(font, 1073.toChar(), 1076.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1040.toChar()) == -1)
    println(getFontCharsKerning(font, 1040.toChar(), 1044.toChar()) == 1)
    println(getFontCharsKerning(font, 1042.toChar(), 1047.toChar()) == -1)
    println(getFontCharsKerning(font, 1057.toChar(), 1051.toChar()) == -1)
    println(getFontCharsKerning(font, 1042.toChar(), 1054.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1057.toChar()) == -1)
    println(getFontCharsKerning(font, 1042.toChar(), 1058.toChar()) == -1)
    println(getFontCharsKerning(font, 1057.toChar(), 1059.toChar()) == -1)
    println(getFontCharsKerning(font, 1061.toChar(), 1060.toChar()) == -1)
    println(getFontCharsKerning(font, 1054.toChar(), 1061.toChar()) == -1)
    println(getFontCharsKerning(font, 1061.toChar(), 1069.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1071.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1072.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1074.toChar()) == -1)
    println(getFontCharsKerning(font, 1075.toChar(), 1076.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1077.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1078.toChar()) == -1)
    println(getFontCharsKerning(font, 1044.toChar(), 1079.toChar()) == 1)
    println(getFontCharsKerning(font, 1043.toChar(), 1080.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1081.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1082.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1083.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1084.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1085.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1086.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1087.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1088.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1089.toChar()) == -1)
    println(getFontCharsKerning(font, 1042.toChar(), 1090.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1091.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1094.toChar()) == -1)
    println(getFontCharsKerning(font, 1074.toChar(), 1095.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1096.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1097.toChar()) == -1)
    println(getFontCharsKerning(font, 1074.toChar(), 1098.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1099.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1100.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1102.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1103.toChar()) == -1)
    println(getFontCharsKerning(font, 1070.toChar(), 1076.toChar()) == -1)
    println(getFontCharsKerning(font, 1044.toChar(), 1063.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1100.toChar()) == -1)
    println(getFontCharsKerning(font, 1069.toChar(), 1061.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1083.toChar()) == -1)
    println(getFontCharsKerning(font, 1056.toChar(), 1044.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1091.toChar()) == -1)
    println(getFontCharsKerning(font, 86.toChar(), 46.toChar()) == -1)
    println(getFontCharsKerning(font, 65.toChar(), 89.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1076.toChar()) == -1)
    println(getFontCharsKerning(font, 1077.toChar(), 1090.toChar()) == -1)
    println(getFontCharsKerning(font, 1056.toChar(), 1072.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1040.toChar()) == -1)
    println(getFontCharsKerning(font, 1100.toChar(), 1095.toChar()) == -1)
    println(getFontCharsKerning(font, 1070.toChar(), 1083.toChar()) == -1)
    println(getFontCharsKerning(font, 65.toChar(), 87.toChar()) == -1)
    println(getFontCharsKerning(font, 89.toChar(), 46.toChar()) == -2)
    println(getFontCharsKerning(font, 1058.toChar(), 44.toChar()) == -2)
    println(getFontCharsKerning(font, 1090.toChar(), 1076.toChar()) == -1)
    println(getFontCharsKerning(font, 1060.toChar(), 1071.toChar()) == -1)
    println(getFontCharsKerning(font, 84.toChar(), 58.toChar()) == -2)
    println(getFontCharsKerning(font, 80.toChar(), 44.toChar()) == -2)
    println(getFontCharsKerning(font, 1042.toChar(), 1095.toChar()) == -1)
    println(getFontCharsKerning(font, 114.toChar(), 44.toChar()) == -1)
    println(getFontCharsKerning(font, 1056.toChar(), 1040.toChar()) == -1)
    println(getFontCharsKerning(font, 1041.toChar(), 1058.toChar()) == -1)
    println(getFontCharsKerning(font, 86.toChar(), 111.toChar()) == -1)
    println(getFontCharsKerning(font, 114.toChar(), 46.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 46.toChar()) == -2)
    println(getFontCharsKerning(font, 86.toChar(), 101.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1044.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1103.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1102.toChar()) == -1)
    println(getFontCharsKerning(font, 1073.toChar(), 1083.toChar()) == -1)
    println(getFontCharsKerning(font, 1050.toChar(), 1060.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1044.toChar()) == -1)
    println(getFontCharsKerning(font, 1100.toChar(), 1090.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1072.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1040.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1054.toChar()) == -1)
    println(getFontCharsKerning(font, 1090.toChar(), 46.toChar()) == -2)
    println(getFontCharsKerning(font, 86.toChar(), 114.toChar()) == -1)
    println(getFontCharsKerning(font, 70.toChar(), 44.toChar()) == -2)
    println(getFontCharsKerning(font, 84.toChar(), 46.toChar()) == -2)
    println(getFontCharsKerning(font, 1040.toChar(), 1058.toChar()) == -1)
    println(getFontCharsKerning(font, 1077.toChar(), 1095.toChar()) == -1)
    println(getFontCharsKerning(font, 1042.toChar(), 1061.toChar()) == -1)
    println(getFontCharsKerning(font, 1056.toChar(), 1077.toChar()) == -1)
    println(getFontCharsKerning(font, 1042.toChar(), 1063.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1097.toChar()) == -1)
    println(getFontCharsKerning(font, 89.toChar(), 45.toChar()) == -1)
    println(getFontCharsKerning(font, 1056.toChar(), 44.toChar()) == -3)
    println(getFontCharsKerning(font, 1060.toChar(), 1051.toChar()) == -1)
    println(getFontCharsKerning(font, 76.toChar(), 32.toChar()) == -1)
    println(getFontCharsKerning(font, 84.toChar(), 59.toChar()) == -2)
    println(getFontCharsKerning(font, 1056.toChar(), 1076.toChar()) == -1)
    println(getFontCharsKerning(font, 1061.toChar(), 1054.toChar()) == -1)
    println(getFontCharsKerning(font, 84.toChar(), 121.toChar()) == -1)
    println(getFontCharsKerning(font, 86.toChar(), 58.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 46.toChar()) == -2)
    println(getFontCharsKerning(font, 1060.toChar(), 1044.toChar()) == -1)
    println(getFontCharsKerning(font, 86.toChar(), 44.toChar()) == -1)
    println(getFontCharsKerning(font, 65.toChar(), 32.toChar()) == -1)
    println(getFontCharsKerning(font, 86.toChar(), 65.toChar()) == -1)
    println(getFontCharsKerning(font, 1060.toChar(), 1058.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1060.toChar()) == -1)
    println(getFontCharsKerning(font, 76.toChar(), 86.toChar()) == -1)
    println(getFontCharsKerning(font, 84.toChar(), 45.toChar()) == -1)
    println(getFontCharsKerning(font, 1060.toChar(), 1059.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1084.toChar()) == -1)
    println(getFontCharsKerning(font, 89.toChar(), 44.toChar()) == -2)
    println(getFontCharsKerning(font, 1059.toChar(), 44.toChar()) == -2)
    println(getFontCharsKerning(font, 1090.toChar(), 1078.toChar()) == 1)
    println(getFontCharsKerning(font, 1073.toChar(), 1098.toChar()) == -1)
    println(getFontCharsKerning(font, 1088.toChar(), 1083.toChar()) == -1)
    println(getFontCharsKerning(font, 86.toChar(), 45.toChar()) == -1)
    println(getFontCharsKerning(font, 87.toChar(), 46.toChar()) == -1)
    println(getFontCharsKerning(font, 1070.toChar(), 1063.toChar()) == -1)
    println(getFontCharsKerning(font, 89.toChar(), 65.toChar()) == -1)
    println(getFontCharsKerning(font, 89.toChar(), 105.toChar()) == -1)
    println(getFontCharsKerning(font, 70.toChar(), 46.toChar()) == -2)
    println(getFontCharsKerning(font, 1040.toChar(), 1063.toChar()) == -1)
    println(getFontCharsKerning(font, 1057.toChar(), 1058.toChar()) == -1)
    println(getFontCharsKerning(font, 84.toChar(), 101.toChar()) == -2)
    println(getFontCharsKerning(font, 1059.toChar(), 1060.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1080.toChar()) == -1)
    println(getFontCharsKerning(font, 1070.toChar(), 1058.toChar()) == -1)
    println(getFontCharsKerning(font, 1091.toChar(), 1076.toChar()) == -1)
    println(getFontCharsKerning(font, 89.toChar(), 97.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1088.toChar()) == -1)
    println(getFontCharsKerning(font, 1056.toChar(), 1086.toChar()) == -1)
    println(getFontCharsKerning(font, 86.toChar(), 121.toChar()) == -1)
    println(getFontCharsKerning(font, 1056.toChar(), 1058.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1077.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1077.toChar()) == -1)
    println(getFontCharsKerning(font, 1079.toChar(), 1095.toChar()) == -1)
    println(getFontCharsKerning(font, 1069.toChar(), 1051.toChar()) == -1)
    println(getFontCharsKerning(font, 84.toChar(), 44.toChar()) == -2)
    println(getFontCharsKerning(font, 1058.toChar(), 1044.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1086.toChar()) == -1)
    println(getFontCharsKerning(font, 70.toChar(), 65.toChar()) == -1)
    println(getFontCharsKerning(font, 1091.toChar(), 44.toChar()) == -2)
    println(getFontCharsKerning(font, 86.toChar(), 59.toChar()) == -1)
    println(getFontCharsKerning(font, 1069.toChar(), 1044.toChar()) == -1)
    println(getFontCharsKerning(font, 1057.toChar(), 1063.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1085.toChar()) == -1)
    println(getFontCharsKerning(font, 1069.toChar(), 1083.toChar()) == -1)
    println(getFontCharsKerning(font, 118.toChar(), 46.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1054.toChar()) == -1)
    println(getFontCharsKerning(font, 1070.toChar(), 1040.toChar()) == -1)
    println(getFontCharsKerning(font, 1056.toChar(), 1061.toChar()) == -1)
    println(getFontCharsKerning(font, 84.toChar(), 99.toChar()) == -2)
    println(getFontCharsKerning(font, 1059.toChar(), 1093.toChar()) == -1)
    println(getFontCharsKerning(font, 84.toChar(), 65.toChar()) == -1)
    println(getFontCharsKerning(font, 1069.toChar(), 1076.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 44.toChar()) == -2)
    println(getFontCharsKerning(font, 1042.toChar(), 1060.toChar()) == -1)
    println(getFontCharsKerning(font, 87.toChar(), 44.toChar()) == -1)
    println(getFontCharsKerning(font, 1042.toChar(), 1057.toChar()) == -1)
    println(getFontCharsKerning(font, 121.toChar(), 46.toChar()) == -1)
    println(getFontCharsKerning(font, 1070.toChar(), 1051.toChar()) == -1)
    println(getFontCharsKerning(font, 1070.toChar(), 1061.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1089.toChar()) == -1)
    println(getFontCharsKerning(font, 1090.toChar(), 44.toChar()) == -2)
    println(getFontCharsKerning(font, 1058.toChar(), 1083.toChar()) == -1)
    println(getFontCharsKerning(font, 1073.toChar(), 1093.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1082.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1074.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1051.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1086.toChar()) == -1)
    println(getFontCharsKerning(font, 87.toChar(), 65.toChar()) == -1)
    println(getFontCharsKerning(font, 1040.toChar(), 1059.toChar()) == -1)
    println(getFontCharsKerning(font, 86.toChar(), 117.toChar()) == -1)
    println(getFontCharsKerning(font, 87.toChar(), 97.toChar()) == -1)
    println(getFontCharsKerning(font, 121.toChar(), 44.toChar()) == -1)
    println(getFontCharsKerning(font, 1091.toChar(), 46.toChar()) == -2)
    println(getFontCharsKerning(font, 1057.toChar(), 1061.toChar()) == -1)
    println(getFontCharsKerning(font, 84.toChar(), 111.toChar()) == -2)
    println(getFontCharsKerning(font, 76.toChar(), 84.toChar()) == -1)
    println(getFontCharsKerning(font, 1056.toChar(), 1051.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1076.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 46.toChar()) == -2)
    println(getFontCharsKerning(font, 1043.toChar(), 1088.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1084.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1102.toChar()) == -1)
    println(getFontCharsKerning(font, 1077.toChar(), 1083.toChar()) == -1)
    println(getFontCharsKerning(font, 1073.toChar(), 1095.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1054.toChar()) == -1)
    println(getFontCharsKerning(font, 80.toChar(), 46.toChar()) == -2)
    println(getFontCharsKerning(font, 84.toChar(), 97.toChar()) == -2)
    println(getFontCharsKerning(font, 32.toChar(), 65.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1087.toChar()) == -1)
    println(getFontCharsKerning(font, 1040.toChar(), 1060.toChar()) == -1)
    println(getFontCharsKerning(font, 1059.toChar(), 1080.toChar()) == -1)
    println(getFontCharsKerning(font, 1042.toChar(), 1059.toChar()) == -1)
    println(getFontCharsKerning(font, 1043.toChar(), 1103.toChar()) == -1)
    println(getFontCharsKerning(font, 1058.toChar(), 1099.toChar()) == -1)
    println(getFontCharsKerning(font, 1075.toChar(), 46.toChar()) == -2)
    println(getFontCharsKerning(font, 1060.toChar(), 1083.toChar()) == -1)
    println(getFontCharsKerning(font, 118.toChar(), 44.toChar()) == -1)
    println(getFontCharsKerning(font, 1056.toChar(), 46.toChar()) == -3)
    println(getFontCharsKerning(font, 1041.toChar(), 1063.toChar()) == -1)
}

/**
 * Gets kerning offset for two characters of the font
 *
 * @param font Font
 * @param char1 First character
 * @param char2 Second character
 * @return offset
 */
fun getFontCharsKerning(font: Font, char1: Char, char2: Char): Int {
    val chars = charArrayOf(char1, char2)
    val withKerningAttrs = HashMap<TextAttribute, Any>()

    withKerningAttrs.put(TextAttribute.FONT, font)
    withKerningAttrs.put(TextAttribute.KERNING, TextAttribute.KERNING_ON)
    val withKerningFont = Font.getFont(withKerningAttrs)
    val withKerningVector = withKerningFont.layoutGlyphVector(
        getFontRenderContext(withKerningFont),
        chars,
        0,
        chars.size,
        Font.LAYOUT_LEFT_TO_RIGHT
    )
    /*val withKerningX = withKerningVector.getGlyphLogicalBounds(1).getBounds().x*/
    /*val withKerningX = withKerningVector.getGlyphVisualBounds(1).bounds2D.x*/
    val withKerningX: Double = withKerningVector.getGlyphLogicalBounds(1).bounds2D.x

    val noKerningAttrs = HashMap<TextAttribute, Any>()
    noKerningAttrs.put(TextAttribute.FONT, font)
    noKerningAttrs.put(TextAttribute.KERNING, 0)
    val noKerningFont = Font.getFont(noKerningAttrs)
    val noKerningVector = noKerningFont.layoutGlyphVector(
        getFontRenderContext(noKerningFont),
        chars,
        0,
        chars.size,
        Font.LAYOUT_LEFT_TO_RIGHT
    )
    /*val noKerningX = noKerningVector.getGlyphLogicalBounds(1).getBounds().x*/
    /*val noKerningX = noKerningVector.getGlyphVisualBounds(1).bounds2D.x*/
    val noKerningX: Double = noKerningVector.getGlyphLogicalBounds(1).bounds2D.x
    return round(withKerningX - noKerningX).toInt()
}

private fun getFontRenderContext(font: Font): FontRenderContext {
    // Canvas works in headless mode
    return Canvas().getFontMetrics(font).getFontRenderContext()
}