name: Compile on Linux

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile on Android
      run: ./gradlew compileDebugKotlinAndroid
    - name: Compile on Desktop
      run: ./gradlew compileKotlinDesktop
    - name: Compile on Js
      run: ./gradlew compileKotlinJs
